// flow-typed signature: 18f97f88303d40b5a2d533d129d3409a
// flow-typed version: <<STUB>>/node-id3_v^0.1.7/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-id3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-id3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-id3/example/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-id3/example/test.js' {
  declare module.exports: $Exports<'node-id3/example/test'>;
}
declare module 'node-id3/index' {
  declare module.exports: $Exports<'node-id3'>;
}
declare module 'node-id3/index.js' {
  declare module.exports: $Exports<'node-id3'>;
}
